In [1]:
import numpy as np

In [2]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
# Valor mayores a 5. Retorna valores boleanos
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
# Como indices mayores a 5 retorna valores a 5. En ese caso usamoo el array para que este valide la información
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [10]:
# Condvalores y condiciones
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

Por ejemplo: Creamos una matriz de una sola dimension con un tamaño de 9 elementos

In [33]:
# Por ejemplo. Generamos una matriz 
arrDos = np.random.randint(0, 10, size=(9))
arrDos

array([5, 8, 6, 3, 8, 2, 1, 8, 5])

In [38]:
# Copiamos el array
arrayDosCopy = arrDos.copy()
arrayDosCopy

array([5, 8, 6, 3, 8, 2, 1, 8, 5])

In [46]:
# Creamos una condición
condicion = arrayDosCopy > 5
condicion

array([False,  True,  True, False,  True, False, False,  True, False])

In [47]:
# Filtramos ocn la condicion creada y almacenada en un varaible
arrayDosCopy[condicion]

array([8, 6, 8, 8])

In [49]:
# Filtramos con esa misma condicion, pero con con valores explicitos
arrayDosCopy[arrayDosCopy > 5]

array([8, 6, 8, 8])

In [50]:
# Realizamos un filtro con una condicion un poco mas explicita
arrayDosCopy[(arrayDosCopy > 4) & (arrayDosCopy < 8)]

array([5, 6, 5])

In [52]:
distribucionNormal = np.random.randn(4)
distribucionNormal

array([ 5.23424452e-01, -1.12021962e-01, -1.79635499e+00, -1.76635442e-03])