In [1]:
import numpy as np

In [3]:
# Array del 0 al 10
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Creamos un slincin
trozo_del_array = arr[0:6]
trozo_del_array

array([0, 1, 2, 3, 4, 5])

In [11]:
# convertimos el trozo del array
trozo_del_array[:] = 0
trozo_del_array

array([0, 0, 0, 0, 0, 0])

In [14]:
# Copiamos el array
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [20]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
# Mostramos el array original
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

NOTA: las funcion copy nos permite copiar el array y no modifica la lista original.