In [2]:
import numpy as np

In [5]:
# Cfeamos una list por ejemplo
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
# Creamos un array. Desde 0 hasta que lo queramos 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Creamos una lista con zeros. Se usa mucho para crear un esquema medio
np.zeros(3)

array([0., 0., 0.])

In [11]:
arryaZeros = np.zeros((10, 10))
print(arryaZeros)
arryaZeros.ndim

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


2

In [16]:
# 10 filas 5 columnas llenos de 1
arrayOnes = np.ones((10, 5))
print(arrayOnes)
print(arrayOnes.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


In [17]:
# Desde 0, hasta 10 y 10 valores
arrayLineSpace = np.linspace(0, 10, 10)
print(arrayLineSpace)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [21]:
# Matriz lineal cuadrada. Donde todos los elementos de la matriz son ceros y la diagonal en 1
arrayEye = np.eye(5)
print(arrayEye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
np.eye(4, 5, -2, dtype='float')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [27]:
# Generar valores aleatorios
np.random.rand()

0.8575850413015893

In [30]:
np.random.rand(4)  # Valores aleatorios de una dimension

array([0.60527202, 0.17305613, 0.1842678 , 0.24997336])

In [31]:
# Vaores alatorios ocn varias dimensiones
np.random.rand(4, 4)

array([[0.46479261, 0.82049201, 0.1118306 , 0.29064803],
       [0.01025795, 0.77682784, 0.76778561, 0.46753425],
       [0.21099184, 0.57156602, 0.62322985, 0.12641685],
       [0.82490708, 0.21995707, 0.10192134, 0.75585962]])

In [36]:
np.random.randint(1, 15)
# NOTA: Sirve para definir el gradient descent o los pesos de una red Neuronal"""

5

In [38]:
# Valores enteros de un valor de 1 hasta 100. Y un array de 10 * 10
np.random.randint(1, 100, (10, 10))

array([[26,  3, 95, 70, 97, 94, 28, 92, 27, 26],
       [39, 21, 15,  2, 86, 89, 70, 18, 42, 84],
       [87, 30,  9, 19, 77, 23, 17, 70,  1, 79],
       [44, 51, 74, 90, 82, 24, 19,  3, 32, 34],
       [81,  3, 45, 20, 12, 22, 92, 42, 48, 17],
       [49, 11, 49, 77, 79, 75, 63, 56, 43, 27],
       [96, 13, 71, 54, 14, 25, 92,  6, 28, 91],
       [92, 57,  2, 33, 84, 81, 24, 10, 65, 11],
       [49, 91, 77,  3, 56, 79, 72, 70, 28, 65],
       [48, 49, 78, 66, 57, 47, 17, 94,  8, 92]])