In [1]:
import numpy as np

Dimensiones:
Scalar: Único valor. No esta dentro de una lista.
Vector: Solamente una dimensión.
Matrix: Cuando hay 2 Dimesiones. Filas y columnas.
Tensor: Se ven en series de tiempo. Ejemplos, características y comportamiento através del tiempo.
Tensor: 4D. Imagenes. Ancho, largo, cantidad de imagenes/ejemplos y canales (Da la composició n de tiempo. )

Tensor: dim = n

In [6]:
# Array scalar
scalar = np.array(42)
print(scalar)
scalar.ndim  # Se imprimen las dimensiones

42


0

In [7]:
# Array Vector
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

In [9]:
# Matriz
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [10]:
# Tensor
tensor = np.array([[[1, 2, 3], [4, 5, 6],  [7, 8, 9],  [10, 11, 12]],  [[1, 2, 3], [4, 5, 6],  [7, 8, 9],  [10, 11, 12]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


3

Agregar o eliminar dimensiones


In [12]:
# Agregar diemensiones. De 10 
vectorDos = np.array([1, 2, 3], ndmin=10)
print(vectorDos)
vectorDos.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [18]:
# Agregar una unica diemsion en sus ejes. 
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [24]:
# imprimimos el vector con sus dimensiones. Eliminamos la dimesniones que no se estan usando
print(vectorDos, vector.ndim)
vectorDos_ = np.squeeze(vectorDos)  # Elimina las dimensiones que no se estan usando
print(vectorDos_, vectorDos_.ndim)  # aca se muestra el vector dos


[[[[[[[[[[1 2 3]]]]]]]]]] 1
[1 2 3] 1
