In [1]:
import numpy as np

In [3]:
array = np.random.randint(1, 20, 10)

In [5]:
# Usamamos el reshape para el cambio de estructura. Dos filas 5 columnas
matriz = array.reshape( 2, 5)
matriz

array([[ 6, 15, 19,  7, 12],
       [19, 14, 14, 19, 19]])

In [6]:
#Coloca mos el array original para comparar
array

array([ 6, 15, 19,  7, 12, 19, 14, 14, 19, 19])

In [7]:
# Buscamos el numero mas grande que tiene el array
array.max()

19

In [9]:
# Buscamos el mismo valor pero en la matris convertida por el aray
matriz.max()

19

In [10]:
# Ahora filtramos el valor maximo por columna
matriz.max(0)

array([19, 15, 19, 19, 19])

In [11]:
# Bsucamos el indice del valor mas grande del array
array.argmax()

2

In [14]:
#  Valor mas grande de la matriz. Pero por columna
matriz.argmax(0)

array([1, 0, 0, 1, 1], dtype=int64)

In [15]:
# Min. Busca el valor mas pequeño del array
array.min()

6

In [16]:
# Busca el indice mas bajo del Buscando valormes minimos. 
array.argmin()

0

In [26]:
# Buscar valores minimos dentro de una matriz
matriz.argmin()

0

In [30]:
# Aca buscamos el valor mas pequeño por columnas
matriz.argmin(0)

array([0, 1, 1, 0, 0], dtype=int64)

In [31]:
# Indice de valores mas pequeños en las filas. Si pasa un parametro en la funcion es para trabajar en los ejes
matriz.argmin(1)

array([0, 1], dtype=int64)

In [37]:
# Aca solo muestra la diferencia entre un valor mas alto y un valor mas alto. Es decir su distancia
array.ptp()

13

In [41]:
# Ahora lotrabajamos por los axis la distancia entre el valor mas bajo y el valor mas alto. Columnas
matriz.ptp(0)

array([13,  1,  5, 12,  7])

In [42]:
# Ahora lo trabajamos por los axis la distancia entre el valor mas bajo y el valor mas alto. Filas
matriz.ptp(1)

array([13,  5])

In [43]:
array

array([ 6, 15, 19,  7, 12, 19, 14, 14, 19, 19])

In [50]:
# Buscar el valor de la mitad. Dependiendo el valor dirá es ellos son menores o iguales al valor que arroje
np.percentile(array, 50)

14.5

In [52]:
# La media y el perceptil son iguales. Nos arroja la media
np.median(array)

14.5

In [54]:
# Tambien lo podemos trabajar por los axis, fila
np.median(matriz, 1)

array([12., 19.])

In [57]:
# Tambien lo podemos trabajar por los axis, columna
np.median(matriz, 1)

array([12., 19.])

In [58]:
# Desviacion estandar. Datos que se dispersan 
np.std(array)

4.651881339845203

In [65]:
# var. Varianza de los datos, desvicion de los datos. El los mismo que desviacion estandar pero elevado al cuadrado 
np.var(array) 

21.64

In [67]:
# La mediana es simplemante la operacion
# de la suma de todos los valores del array, entra la cantidad
np.mean(array)

14.4

In [99]:
# AL usar concatenate, deben ser los arrays de las misma dimesiones
a = np.array([[1, 2], [3,4]])
b = np.array([5,6])
#np.concatenate((a, b), axis=0)

In [100]:
# Validamos la dimensinones de b
b.ndim

1

In [101]:
# Expandimos las direcciones de b.
b = np.expand_dims(b, axis=0)
b

array([[5, 6]])

In [102]:
# Lo concatenenamos por filas y columas.
np.concatenate((a, b), axis=0) 

array([[1, 2],
       [3, 4],
       [5, 6]])