In [2]:
import numpy as np

In [3]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
arrayLista = np.array(lista)
arrayLista

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
type(arrayLista)

numpy.ndarray

In [14]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#Indexin
arrayLista

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arrayLista[1] # Buscamos posicion 1

2

In [17]:
# Sumamos posiciones
arrayLista[0] + arrayLista[5]

7

In [26]:
# Volvemos a imprimir el array
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# Usamos la matriz bidimensional
matriz[0, 2]

3

In [31]:
#Slincing. Desde hasta
arrayLista[0:2]

array([1, 2])

In [32]:
#Slincing. Desde hasta
arrayLista[1:9]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#Slinsing. Traer datos de a 2
arrayLista[0: 9: 2]

array([1, 3, 5, 7, 9])

In [37]:
# Imprimmos la matriz
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
#Slinsing. Desde la fila 1, columna 0 y 1
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])