In [1]:
import numpy as np

Tipos de Datos


In [18]:
# Creamos el array
arrInt = np.array([1, 2, 3, 4])
arrInt

array([1, 2, 3, 4])

In [19]:
# Buscamos el tipo de dato array
arrInt.dtype

dtype('int32')

In [20]:
# Damos propiedad en la definision del array
# Creamos el array
arrFloat = np.array([1, 2, 3, 4], dtype='float64')
arrFloat.dtype

dtype('float64')

In [21]:
# Aca ya sabemos que el tipo de dato es decimal
arrFloat

array([1., 2., 3., 4.])

In [22]:
# imprmimos el array de tipo entero
arrInt

array([1, 2, 3, 4])

In [25]:
# Pasamos de tipo de dato entero a tipo float
arrInt = arrInt.astype(np.float64)
arrInt.dtype

dtype('float64')

In [33]:
# Ahora lo pasamos de int a Booleano
arrIntDos = np.array([0, 1, 2, 3, 4])
arrIntDos = arrIntDos.astype(np.bool_)
arrIntDos

array([False,  True,  True,  True,  True])

In [34]:
# Array de tipo string con numeros
arrString = np.array([0, 1, 2, 3, 4])
arrString = arrString.astype(np.string_)
arrString

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [36]:
arrStringInt = np.array(['0', '1', '2', '3', '4'])
arrStringInt = arrStringInt.astype(np.int32)
arrStringInt

array([0, 1, 2, 3, 4])

NOTA: El arrray siempre va a tener único tipo de datos dentro de el