In [1]:
import numpy as np

In [2]:
lista = [1, 2]
lista

[1, 2]

In [3]:
# Multiplicar una lista
lista * 2

[1, 2, 1, 2]

In [6]:
# en realidad se hace con python
arr = np.arange(0, 10)
arrTwo = arr.copy()

In [8]:
# Esto si multiplica el array, mientras que en la lista de python solo hace es duplicar los resultados
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# sumar un valor a los datos
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
# Hace la division en tre valores
1 / arr

C:\Users\tronc\AppData\Local\Temp\ipykernel_57636\1470831230.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
# sumamos arrays
arr + arrTwo

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# Restamos los arrays
arr - arrTwo

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Exponemos al cuadrado
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [20]:
matriz = arr.reshape(2, 5)
matrizDos = matriz.copy()


In [21]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
matrizDos

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
matrizDos.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [28]:
# Operación algebraica
np.matmul(matriz, matrizDos.T)

array([[ 30,  80],
       [ 80, 255]])

In [30]:
matriz @ matrizDos.T  # Operaciones de producto punto

array([[ 30,  80],
       [ 80, 255]])

In [37]:
quiz = np.array([[1, 2, 3],  [4, 5, 6], [7, 8, 9]])
quiz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])