In [1]:
import numpy as np

In [4]:
# Creamos un array con valores de 1 a 10. De 3 * 2
array = np.random.randint(1, 10, (3, 2))
array

array([[9, 9],
       [7, 9],
       [6, 8]])

In [5]:
# Shape da la forma de un arreglo. Da con que estructura se esta trabajando
array.shape

(3, 2)

In [7]:
# NOTA: Se usa en redes neuronales con una forma especifica.
array.reshape(1, 6)  # Cambia la forma que tnego establecida en un array

array([[9, 9, 7, 9, 6, 8]])

In [9]:
# Tambien podemos pasarlo de estrustura propia dada. Por ejemplo. Reshape 2 filas y 3 columnas
array.reshape(2, 3)

array([[9, 9, 7],
       [9, 6, 8]])

In [11]:
np.reshape(array, (1, 6))  # Lo volvemos de una sola dimension

array([[9, 9, 7, 9, 6, 8]])

In [14]:
# Array original
array

array([[9, 9],
       [7, 9],
       [6, 8]])

In [17]:
np.reshape(array, (2, 3), 'C')  # Estructura 2 * 3 como lo hace el lenguaje c. Lo hace por filas

array([[9, 9, 7],
       [9, 6, 8]])

In [18]:
np.reshape(array, (2, 3), 'F')  # ESte lo hace ppr columna

array([[9, 6, 9],
       [7, 9, 8]])

In [20]:
np.reshape(array, (2, 3), 'A')  # Lo hace de forma como lo hace la laptop

array([[9, 9, 7],
       [9, 6, 8]])