In [1]:
import numpy as np 

Obtener Versión y Configuración de Numpy

In [2]:
np.__version__

'1.23.5'

Obtener Información de la Función add de Numpy

In [4]:
np.info(np.add)  # Obtenemos informacion de la funcion add de numpy

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Comprobar si un Arreglo tiene Elementos Igual a Cero

In [12]:
# Validamos si el arreglo tiene almenos un elemento igual a cero, retorna false y si no hay es true
arr = [1, 2, 3, 4, 0]  
np.all(arr)

False

 Comprobar si en un Arreglo Existe al menos un Elemento Distinto de Cero

In [25]:
#Arreglo
a = np.array([1, 2, 3, 4, 5, 0])
print(a)

# Validamos si almenos un elemento es distinto de cero. Si lo hay devuelde True y False Si no es asi
print(np.any(a))

# Validamos si al menos un elemento es distinto de 0, devuelve Flase, por que nunguno de ellos es distinto de 0
b = np.array([0, 0, 0])  # Todos son iguales a cero

print(b)
print(np.any(b))

[1 2 3 4 5 0]
True
[0 0 0]
False


Comprobar si los Elementos de un Arreglo son Finitos

In [32]:
# validamos si estos valores son finitos. Es decir son elementos contables y elementos definidos.
c = np.array([1, 2, 3, 4, 5, -np.inf])
print(c)
np.isfinite(c)

[  1.   2.   3.   4.   5. -inf]


array([ True,  True,  True,  True,  True, False])

Comprobar si los Elementos de un Arreglo son Infinitos

In [38]:
# Arreglo.
d = np.array([1, 2, 3, 4, 5, -np.inf])
print(d)

# Validamos si alguno de los elementos son infinitos, devuelve true de lo contrario devuelve false.
np.isinf(d)

[  1.   2.   3.   4.   5. -inf]


array([False, False, False, False, False,  True])

Comprobar si los Elementos de un Arreglo NumPy son Nulos

In [41]:
e = np.array([1, 2, 3, 4, 5, -np.inf, np.nan])

# Mostramos el array
print(e)

# Validamos si el arreglo tiene valores NaN. Devuelve True si alguno de los elementos son NaN. 
np.isnan(e)


[  1.   2.   3.   4.   5. -inf  nan]


array([False, False, False, False, False, False,  True])

Comprobar si cada Elemento de un Arreglo es un Número Real, Complejo, o Escalar

In [49]:
f = np.array([1, 2, 3, 4, 5, -np.inf, np.nan, 0.+2.j, 5.5])

# Msotrarr arreglo
print(f)

#Validar si es un elemento de tipo complejo. Devuelve True si hay un numero ocmplejo. De lo contrario devuelve False
print(np.iscomplex(f))

# validamos si es un numero real. Devuelve True si hay numeros reales y false si hay numeros complejos
print(np.isreal(f))

# Validamos si hay numeros escalar. No se le puede pasar un arreglo de valores, debe de ser un numero solamente. De lo contrario devuelve false
print(np.isscalar(f))

[ 1. +0.j  2. +0.j  3. +0.j  4. +0.j  5. +0.j -inf+0.j  nan+0.j  0. +2.j
  5.5+0.j]
[False False False False False False False  True False]
[ True  True  True  True  True  True  True False  True]
False


Comprobar si Dos Arreglos son Iguales Bajo un Grado de Tolerancia

In [64]:
# Toma los valores por iguald y deben de ser iguales al compararlos
g = np.array([1, 2, 3, 4, 5, 0, np.nan])
h = np.array([1, 2, 3, 4, 5, 0, np.nan])

print(np.allclose(g, h, equal_nan=True))  # Si le pasamos el tercer parametro que acepte los elementos NaN.

True


Aplicar Operadores Relacionales a Cada Elemento de Dos Arreglos

In [78]:
i = np.array([1, 2, 3, 4, 5, 1, np.nan])
j = np.array([1, 2, 3, 4, 5, 0, np.nan])

print(i)
print(j)

# Validamos si los arreglos tiene valores menores que el otro. Es decir el valor de i es o no mayor que uno de los valores j
print(np.less(i, j))


# Validamos los arreglos del primer elementos con los arreglos del segundo elemento son iguales. Los vcalos de tipos NaN no los toma
print(np.less_equal(i, j))


print(np.greater(i, j))

#  

[ 1.  2.  3.  4.  5.  1. nan]
[ 1.  2.  3.  4.  5.  0. nan]
[False False False False False False False]
[ True  True  True  True  True False False]
[False False False False False  True False]


 Comprobar Igualdad con Tolerancia Elemento a Elemento de Dos Arreglos

In [81]:
k = np.array([1, 2, 3, 4, 5, 1, np.nan])
n = np.array([1, 2, 3, 4, 5, 3.00000, np.nan])
print(k)
print(n)

#Se debe espeficicar la tolerancia
print(np.isclose(k, n))

[ 1.  2.  3.  4.  5.  1. nan]
[ 1.  2.  3.  4.  5.  3. nan]
[ True  True  True  True  True False False]


Obtener el Tamaño en Bytes que Ocupa un Arreglo NumPy

In [88]:
m = np.array([2, 3, 5, 7, 11])
print(m.size)

# Calculamos el tamaño en bytes que ocupa un arreglo
m.size * a.itemsize

5


20

Crear Tres Arreglos con 10 Ceros, 10 Unos, y 10 Sietes

In [91]:
ñ = np.zeros(10)
o = np.ones(10)
p = np.ones(10) * 7
print(ñ)
print(o)
print(p)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


 Crear un Arreglo con Enteros entre 20 y 50

In [93]:
q = np.arange(20, 50)
print(q)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


Crear un Arreglo con Enteros Pares entre 20 y 50

In [98]:
r = np.arange(20, 51, 2)
print(r) 
print(type(r))

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
<class 'numpy.ndarray'>


Crear una Matriz Identidad

In [ ]:
# La matriz de indetidad debe de ser cuadrada
