In [1]:
import pandas as pd
import numpy as np

Convertir un Objeto Series con Múltiples Listas en un Único Objeto Series

In [8]:
datosLista = [['Colombia', 'Perú', 'Argentina'], ['Bolivia', 'Uruguay'], ['Chile']]
serie = pd.Series(datosLista)
print(serie)
print(type(serie))

0    [Colombia, Perú, Argentina]
1             [Bolivia, Uruguay]
2                        [Chile]
dtype: object
<class 'pandas.core.series.Series'>


In [11]:
# toma el objeto serie lo cambia a stack para convertirlo en una sola
# Linea y resetea la columnas
objetoMúltiplesListas = serie.apply(pd.Series).stack().reset_index(drop=True)
objetoMúltiplesListas

0     Colombia
1         Perú
2    Argentina
3      Bolivia
4      Uruguay
5        Chile
dtype: object

In [15]:
print(serie.explode())
print(type(serie))

0     Colombia
0         Perú
0    Argentina
1      Bolivia
1      Uruguay
2        Chile
dtype: object
<class 'pandas.core.series.Series'>


Ordenar los Valores de un Objeto Series con el Método sort_values

In [21]:
datos = ['1.1', 'Python', '0.5', 'Pandas', '2.8']
print(type(datos))
serieDos = pd.Series(datos)
print(serieDos)
print(type(serieDos))

<class 'list'>
0       1.1
1    Python
2       0.5
3    Pandas
4       2.8
dtype: object
<class 'pandas.core.series.Series'>


In [26]:
serieDos.sort_values()

2       0.5
0       1.1
4       2.8
3    Pandas
1    Python
dtype: object

Agregar Más Datos a un Objeto Series Existente

In [32]:
datosDos = ['C#', 'Python', 'Java', 'Pandas']
nuevosDatos = ['React', 'Nodejs']

dfDos = pd.Series(datosDos)
dfTres = pd.Series(nuevosDatos)

print(dfDos)
print(dfTres)


0        C#
1    Python
2      Java
3    Pandas
dtype: object
0     React
1    Nodejs
dtype: object


In [35]:
concatenacion = pd.concat([dfDos, dfTres])
concatenacion

0        C#
1    Python
2      Java
3    Pandas
0     React
1    Nodejs
dtype: object

Crear un Objeto Series a partir de un Filtro Aplicado a otro Objeto Series

In [52]:
# creamos el objeto serie
dfCuatro = pd.Series([ 1, 2, 4, 8, 4, 25, 90])

# Imprimimos el objeto serie
print(dfCuatro)
# Imprimios el objeto serie
print(type(dfCuatro))

# Haemos la condicion
condicion = dfCuatro[dfCuatro > 5]
print(condicion)

# Imprimimos el tipo de dato de la condici
print(type(condicion))

0     1
1     2
2     4
3     8
4     4
5    25
6    90
dtype: int64
<class 'pandas.core.series.Series'>
3     8
5    25
6    90
dtype: int64
<class 'pandas.core.series.Series'>


Cambiar el Orden de los Índices de un Objeto Series

In [84]:
listaNumeros = [ 1, 2, 4, 8]
indices = ['A', 'B', 'C', 'D']

serieTres = pd.Series(data=listaNumeros, index=indices)
print(serieTres)

A    1
B    2
C    4
D    8
dtype: int64


In [87]:
serieTres = serieTres.reindex(index=['B', 'A', 'D', 'C'])
print(serieTres)
# Nota: Se cambian el orden de los indices, pero su valor es el anterior

B    2
A    1
D    8
C    4
dtype: int64


Calcular la Desviación Estándar y el Promedio de un Objeto Series

In [94]:
datosDos = [2, 4, 5, 6, 7, 9, 20, 41, 60, 100]
serieCautro = pd.Series(datosDos)
serieCautro

# Desviacion estandar
print(serieCautro.std())

# Calculamos la media
print(serieCautro.mean())

32.387240285849195
25.4


Calcular los valores mínimo y máximo de un objeto serie

In [98]:
datosTres = [2, 4, 5, 6, 7, 9, 20, 41]
serieCinco = pd.Series(datosDos)

# Objeto Serie
print(datosTres)

# Valor minimo
print(serieCinco.min())

# Valor maximo
print(serieCinco.max())

[2, 4, 5, 6, 7, 9, 20, 41]
2
100


Obtener estadisticas basicas de un ovjeto serie

In [103]:
datosCuatro = list(range(15))
serieSeis = pd.Series(datosCuatro)

#Estadisticas basicas
serieSeis.describe()

count    15.000000
mean      7.000000
std       4.472136
min       0.000000
25%       3.500000
50%       7.000000
75%      10.500000
max      14.000000
dtype: float64

Obtener los elementos pares e impares ee un objeto serie

In [115]:
datosSeis = list(range(15))
serieSiete = pd.Series(datosSeis)

# Objeto serie
#print(serieSeis)

# Buscar valores pares de un objeto serie
pares = serieSiete[serieSiete % 2 == 0]
print( pares)

# Elementos impares:
impares = serieSiete[serieSiete % 2 == 1]
print(impares)

0      0
2      2
4      4
6      6
8      8
10    10
12    12
14    14
dtype: int64
1      1
3      3
5      5
7      7
9      9
11    11
13    13
dtype: int64


Extraer los datos de un objeto serie como objeto Numpy

In [124]:
# Creamos una lista como objeto 
datosSiete = list(range(15))
print(datosSiete)

# Creamos un arreglo de tipo serie
objetoSerie = pd.Series(datosSiete)
print(type(objetoSerie))

# Convertimos el objeto serie a una arreglo numpy
objetoNumpy = objetoSerie.values  # Con el value al final de puede pasar a numpy
print(objetoNumpy)
print(type(objetoNumpy))
objetoNumpy



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
<class 'pandas.core.series.Series'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int64)

 Comprobar si una Serie contiene Valores NaN con hasnans

In [140]:
datosCinco = ['Python', '30', '20', 100, None]
serieOcho = pd.Series(datosCinco)

# Busca si hay valores boleanos, si hay devuelve true y si no hay flase
print(serieOcho.isna())

# Busca si hay valores booleanos, si hay devuelve false y si no deuvle true
print(serieOcho.notna())

# Verificar con hasnans. Comprueba si POR LO MENOS un valor en la serie tiene
# un valor de tipos NaN
print(serieOcho.hasnans)

# Convertimos la lista a valores numeros y dado el caso quen o pueda lo coloque como NaN
serieOcho = pd.to_numeric(serieOcho, errors='coerce')
print(serieOcho)


0    False
1    False
2    False
3    False
4     True
dtype: bool
0     True
1     True
2     True
3     True
4    False
dtype: bool
True
0      NaN
1     30.0
2     20.0
3    100.0
4      NaN
dtype: float64


Obtener el tamaño en bytes del espacio que ocupan los elementos de un objeto series

In [143]:
datosOcho = list(range(10))
serieNueve = pd.Series(datosOcho)

# Objeto serie
print(serieNueve) 

# tamaño en bytes. Cada elemento una un cierto numero de bytes de todo el elemnte
serieNueve.nbytes

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


80

Usas los metodos add, substracm multiply y divide

In [152]:
serieDies = pd.Series(list(range(1, 10)))
serieOnce = pd.Series(list(range(10, 0, -1)))

# Series
print(serieDies)
print(serieOnce)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
0    10
1     9
2     8
3     7
4     6
5     5
6     4
7     3
8     2
9     1
dtype: int64


In [154]:
# Usamos el add
print(serieDies.add(serieOnce))

0    11.0
1    11.0
2    11.0
3    11.0
4    11.0
5    11.0
6    11.0
7    11.0
8    11.0
9     NaN
dtype: float64


In [155]:
# Usamos substract
print(serieDies.subtract(serieOnce))

0   -9.0
1   -7.0
2   -5.0
3   -3.0
4   -1.0
5    1.0
6    3.0
7    5.0
8    7.0
9    NaN
dtype: float64


In [156]:
#Usamos divide
print(serieDies.divide(serieOnce))

0    0.100000
1    0.222222
2    0.375000
3    0.571429
4    0.833333
5    1.200000
6    1.750000
7    2.666667
8    4.500000
9         NaN
dtype: float64


Eliminar los valor NaN de una serie con el Método dropna

In [164]:
datosNueve = ['Python', '30', '20', 100, None, np.nan]
serieDoce = pd.Series(datosNueve)

#Mostramos el objeto serie
print(serieDoce)

# Los que no se pueden covertir a numeros los colocar como NaN y los elimina 
serieDoce = pd.to_numeric(serieDoce, errors='coerce')
print(serieDoce)

# Mostramos la nueva serie con los datos eliminado con dropna
print(serieDoce.dropna())

0    Python
1        30
2        20
3       100
4      None
5       NaN
dtype: object
0      NaN
1     30.0
2     20.0
3    100.0
4      NaN
5      NaN
dtype: float64
1     30.0
2     20.0
3    100.0
dtype: float64


Calcular el valor absoluto de todos los elementos de un bojeto series

In [166]:
datosDies = [3, -5, 1, -8, 3, -7]
serieTrece = pd.Series(datosDies)

# Valores abosluto
print(serieTrece.abs())

0    3
1    5
2    1
3    8
4    3
5    7
dtype: int64


Usar la funcion agg de un objeto series

In [174]:
from math import sqrt
datosOnce = [3, -5, 1, -8, 3, -7]
serieCatorce = pd.Series(datosOnce)
# Msotramos la serie
print(serieCatorce)

0    3
1   -5
2    1
3   -8
4    3
5   -7
dtype: int64


In [189]:
# Pasamos el valor mayor del objeto serie.
serieCatorce.agg(max)

3

In [190]:
# Valos minimo de el objeto serie
serieCatorce.agg(min)

-8

In [191]:
# Valor abosluto de cada elemento
serieCatorce.agg(abs)

0    3
1    5
2    1
3    8
4    3
5    7
dtype: int64

In [192]:
# A cada valor aboluto de un numero le sacamos la raiz cuadrada
serieCatorce.agg(abs).agg(sqrt)

0    1.732051
1    2.236068
2    1.000000
3    2.828427
4    1.732051
5    2.645751
dtype: float64

In [193]:
serieCatorce.agg(abs).agg(hex)  # Valores hexadecimales

0    0x3
1    0x5
2    0x1
3    0x8
4    0x3
5    0x7
dtype: object

In [194]:
def cuadrado(x):
    return x * x

serieCatorce.agg(cuadrado)  # Pasamos cada elemento y lo multiplicamos por el mismo

0     9
1    25
2     1
3    64
4     9
5    49
dtype: int64

In [195]:
serieCatorce.agg(lambda x: x ** 3)  # Todos a la 3

0     27
1   -125
2      1
3   -512
4     27
5   -343
dtype: int64

In [196]:
serieCatorce.agg(np.sin)  # Seno de cada elemento

0    0.141120
1    0.958924
2    0.841471
3   -0.989358
4    0.141120
5   -0.656987
dtype: float64

In [197]:
serieCatorce.agg(np.cbrt)  # Raiz cubica de cada elemento

0    1.442250
1   -1.709976
2    1.000000
3   -2.000000
4    1.442250
5   -1.912931
dtype: float64

In [199]:
serieCatorce.agg(np.sum)  # sumatoria de todo el arreglo pnadas.

-13

In [214]:
array = np.ones()
array



array([1.])

In [216]:
ejemplo = [1, 2, 3, 4]
s = pd.Series(ejemplo)
print(s)
print(s.isnull())


0    1
1    2
2    3
3    4
dtype: int64
0    False
1    False
2    False
3    False
dtype: bool


In [225]:
arr = np.array([1, 2, 3, 4, 7])
arr.des


4