In [40]:
import numpy as np

In [41]:
matrizUno = np.array([[1, -1, 2], [3, 2, 0]])
print(matrizUno)

[[ 1 -1  2]
 [ 3  2  0]]


In [42]:
matrizDos = np.array([[1], [2], [3]])
print(matrizDos)

[[1]
 [2]
 [3]]


In [43]:
# Pasamos de matriz filas a columnas o viceversa
print(np.transpose(matrizUno))

[[ 1  3]
 [-1  2]
 [ 2  0]]


In [44]:
matrizTres = np.array([[1, 2, 3]])
print(np.transpose(matrizTres))

[[1]
 [2]
 [3]]


In [45]:
""" Sistemas de ecuaciones. Resuelve la ecuación A x = b """
print('     Sistemas de ecuciones ejercicio Uno: ')
a = np.array([[2, 1, -2], [3, 0, 1], [1, 1, -1]])
print(a)

     Sistemas de ecuciones ejercicio Uno: 
[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]


In [46]:
b = np.array([[-3], [5], [-2]])
print(b)

[[-3]
 [ 5]
 [-2]]


In [47]:
# Transponemos a b
print(np.transpose(b))

[[-3  5 -2]]


In [48]:
# Aca resolvemos el punto de algébra lineal
x = np.linalg.solve(a, b)
print(x)

[[ 1.]
 [-1.]
 [ 2.]]


In [49]:
# Validamos si el resultado es correcto no
print(np.allclose(np.dot(a, x), b))
# El primer elemento es la matriz mas grande, el segundo es el resultado y el tercero la matriz comparada.

True


In [72]:
""" Sistemas de ecuaciones"""
print('     Sistemas de ecuciones ejercicio Dos: ')
matrizMUno = np.array([[2, 7, 3], [2, 8, 2], [1, 3, 1]])
print(matrizMUno)

     Sistemas de ecuciones ejercicio Dos: 
[[2 7 3]
 [2 8 2]
 [1 3 1]]


In [73]:
matrizMDos = np.array([1, 1, 0])
print(matrizMDos)

[1 1 0]


In [74]:
# Hacemos el cambio de dirección de la matriz
matrizMDos.shape=(3, 1)
print(matrizMDos)

[[1]
 [1]
 [0]]


In [75]:
# Resolvemos la ecuación
resultados = np.linalg.solve(matrizMUno, matrizMDos)

In [76]:
# Acá avalamos el resultado
print(np.allclose(np.dot(matrizMUno, resultados), matrizMDos))

True
