In [36]:
import numpy as np

In [37]:
# Matriz de dos dimensiones
matriz = np.array([[1, 2, 3 ], [4, 5, 6], [7, 8, 9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
# Elemento maximo
print(np.amax(matriz))

9


In [39]:
# Elemento minímo de la filas. Main 1
print(np.amin(matriz, 1))

[1 4 7]


In [40]:
# Elemento minímo de la columnas. Main 0
print(np.amin(matriz, 0))

[1 2 3]


In [41]:
# Restamos el valor maximo y el minímo de la matriz
print(np.ptp(matriz))

8


In [42]:
# Restamos el valor maximo y el minímo de cada fila
print(np.ptp(matriz, axis=1))

[2 2 2]


In [43]:
# Perceptiles. Comparamos un conjunto ordenado de datos. Formula perceptil = q(n + 1) / 100
print(np.percentile(matriz, 50))  # El valor de q es 50
"""Solo funciona cuando los elementos de mi matriz es impar"""

5.0


'Solo funciona cuando los elementos de mi matriz es impar'

In [44]:
# Perceptiles. Comparamos un conjunto ordenado de datos. Formula perceptil = q(n + 1) / 100
print(np.percentile(matriz, 50, axis= 1))

[2. 5. 8.]


In [45]:
# Mediana. mediana = (n +1)/2
print(np.median(matriz))

5.0


In [46]:
# Mediana. mediana = (n + 1)/2
print(np.median(matriz, axis=0))

[4. 5. 6.]


In [47]:
# Media aritmética = x1 + x2.... xn / n
print(np.mean(matriz))
# Se suman todos los elementos de la matriz y se dividen en la cantidad de elementos(n)

5.0


In [48]:
# Matriz de una sola dimension. el promedio ponderado = x1 * p1... xn * pn / Ep
matriz1 = np.array([1, 2, 3, 4, 5, 6])
print(np.average(matriz1))  # Promedio ponderado
# Peso es igual a 1 para ejemplo


3.5


In [49]:
# Desviación estándar. Entre mayor sea la desviación mayor será la dispersión de los datos
print(np.std(matriz1))

1.707825127659933
