1. Importar numpy

In [37]:
# Import numpy y matpltlib.pyplty para los graficos
import numpy as np
import matplotlib.pyplot as plt

2. Crear un array de numpy partiendo de una lista

In [38]:
# Creamos una lista
lista = [31, 28, 29, 19]
# Pasamos la lista a un arreglo
arr = np.array(lista)
print(arr)

[31 28 29 19]


3. Crear un array de numpy bidimensional partiendo de una lista 

In [39]:
# Creamos una lista 2D
listaDosD = [[2, 3, 4], 
             [3, 4, 5],
             [3, 4, 5],
             [3, 4, 5]]

# PAsamos la lista a un array con numpy
arrDosD = np.array(listaDosD)
print(arrDosD)

[[2 3 4]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


4. Utilizar la propiedad shape y obtener el array anterior

In [40]:
print(arrDosD.shape)

(4, 3)


Utilizar la propiedad ndim y obtener las dimensiones del array anteriror

In [41]:
print(arrDosD.ndim)

2


Utilizar la propiedad dtype y obtener el tipo de dato array anteriror

In [42]:
print(arrDosD.dtype)

int32


Cuantos datos hay entotal en el array

In [44]:
print(arrDosD.size)

12


5. Crea un ndarray utilizando una lista. El tipo de dato deber ser int16

In [49]:
arr = np.array(listaDosD, dtype=np.int16)
print(f'Tipo de dato de la matriz: {arr.dtype}')
print(arr)

Tipo de dato de la matriz: int16
[[2 3 4]
 [3 4 5]
 [3 4 5]
 [3 4 5]]
