Let´s star with numpy

In [1]:
import numpy as np

In [4]:
# Array sin contenido, vacio
np.empty((4, 8))

array([[8.71925338e-312, 1.05730048e-321, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307, 5.02034658e+175,
        4.69911253e-033, 3.24665698e-057],
       [2.04028652e+160, 1.48576100e-076, 4.30868404e-033,
        4.26309070e-096, 1.12855837e+277, 8.93168725e+271,
        7.33723594e+223, 1.70098498e+256],
       [5.49109388e-143, 1.06396443e+224, 3.96041428e+246,
        1.16318408e-028, 8.70409996e-071, 8.61133746e-043,
        8.46734393e+165, 2.62977609e-052],
       [2.24151504e+174, 3.36163259e-067, 5.41905470e-067,
        2.04375485e-028, 3.93990098e-062, 5.74015544e+180,
        1.94919988e-153, 6.79764374e-310]])

In [6]:
# Crear arrays iniciandos en ceros
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
# Crear arrays inicializados en 1
np.ones((4, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
# Creamos un array inicializados en 7
np.full((4, 8), 7)

array([[7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [11]:
# Generamos un arrays con valores aleatorios
np.random.rand(4, 8)

array([[0.79945354, 0.54148018, 0.49565579, 0.02314464, 0.49040714,
        0.977809  , 0.30063502, 0.22481085],
       [0.40305065, 0.7714616 , 0.15447863, 0.56393613, 0.08792703,
        0.18218154, 0.71020047, 0.16355426],
       [0.9415894 , 0.74574814, 0.87062971, 0.37690382, 0.89591204,
        0.2968458 , 0.71268186, 0.30962473],
       [0.48504807, 0.5370767 , 0.15136635, 0.98297197, 0.20989217,
        0.5053443 , 0.46949732, 0.43304721]])

In [23]:
# Generamos un array de valores enteros. De una sola dimension
myArray = np.random.randint(0, 10, 32)
# Colocamos el array de manera bidimensional. Pasos por referencia
myArrayResahpe = np.reshape(myArray, (4,8))
print(myArrayResahpe)

[[6 2 9 6 4 8 9 3]
 [5 0 6 8 6 6 6 1]
 [9 1 1 7 5 6 9 1]
 [4 8 4 5 6 3 1 5]]


In [24]:
# Pasar de lista a array
np.array([7, 7, 7])

array([7, 7, 7])

In [26]:
# Pasar una lista a un array
np.array([[1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8]])

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [27]:
# Creacion de array con rangos
np.linspace(0, 10, 32)

array([ 0.        ,  0.32258065,  0.64516129,  0.96774194,  1.29032258,
        1.61290323,  1.93548387,  2.25806452,  2.58064516,  2.90322581,
        3.22580645,  3.5483871 ,  3.87096774,  4.19354839,  4.51612903,
        4.83870968,  5.16129032,  5.48387097,  5.80645161,  6.12903226,
        6.4516129 ,  6.77419355,  7.09677419,  7.41935484,  7.74193548,
        8.06451613,  8.38709677,  8.70967742,  9.03225806,  9.35483871,
        9.67741935, 10.        ])

In [30]:
# Buscamos le tamaño del array
np.linspace(0, 10, 32).shape

(32,)

In [32]:
# Rando dle array
np.linspace(0, 10, 32).ndim

1

In [33]:
# Size del array
np.linspace(0, 10, 32).size

32

In [35]:
# Bloque de array. Suma de array
muyArrayOne = np.array([7, 7, 3])
myArrayTwo = np.array([3, 3, 5])
print(muyArrayOne + myArrayTwo)

[10 10  8]


In [39]:
# Bloque de array. Suma de array. De una sola dimensión
myArrayThree = np.array([[7, 7, 3], [1, 2, 3]])
myArrayFour = np.array([3, 3, 5])
print(myArrayThree + myArrayFour)

[[10 10  8]
 [ 4  5  8]]


In [41]:
# Obtener la media
myArrayFive = np.array([7, 7, 3])
myArrayFive.mean()

5.666666666666667

In [42]:
# Suma de los valores de los array
myArrayFive.sum()

17

In [46]:
# Filtra un array por poscisión dimensional
myArraySix = np.array([7, 13, 7])
print(myArraySix[1])


13


In [52]:
# Filtra un array por poscisión bidimensional
myArraySeven = np.array([[7, 13, 7], [8, 9, 2]])
print(myArraySeven[1, 2])

2


In [57]:
# Accediendo con Slicings. Desde 0 hasta 1
myArraySeven[0: 1]

array([[15, 13,  7]])

In [58]:
# Desde 0 hasta 2
myArraySeven[0: 2]

array([[15, 13,  7],
       [ 8,  9,  2]])

In [59]:
# Todos le array
myArraySeven[0::]

array([[15, 13,  7],
       [ 8,  9,  2]])

In [60]:
# Modificar el valor de una poscisión
myArraySeven[0, 0] = 15
myArraySeven

array([[15, 13,  7],
       [ 8,  9,  2]])

In [61]:
# Pasar de una sola dimensión
myArrayEight = np.array([[7, 13, 7], [2, 8, 9]])
myArrayEight.ravel()

array([ 7, 13,  7,  2,  8,  9])